package com.mytwitter.app;

import java.io.IOException;

import com.mytwitter.routes.LogRouteAdapter;
import com.mytwitter.routes.Routes;

import dataservice.DataService;
import dataservice.MybatisDataService;
import spark.Spark;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

	public static void main(String[] args) throws IOException {

		Spark.staticFiles.location("/webapp/");
		DataService dataService = new MybatisDataService();
		Routes routes = new Routes(dataService);
		routes.addRouteListener(new LogRouteAdapter());
		routes.start();
		/*
		RestTemplate rt = new RestTemplate();
		Post post = rt.getForObject("http://localhost:4567/api/post/1", Post.class);
		System.out.println("PostId:" + post.getPostId());
		System.out.println("Text:" + post.getText());
		*/
	}
}
